AWSTemplateFormatVersion: 2010-09-09
Description: AWS-Study Template

Parameters:
  # RDSのパラメーター
  DBUsername:
    Description: RDSのマスターユーザー名
    Type: String
    Default: root
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"

  DBPassword:
    Description: RDSのマスターパスワード
    Type: String
    NoEcho: true
    Default: L2202670970
    MinLength: 8
    MaxLength: 41
  
  # IAMポリシー
  ExistingUserName:
    Type: String
    Default: L2202670970

# RDSの作成
Outputs:
  RDSInstanceEndpoint:
    Description: RDSのエンドポイント
    Value: !GetAtt RDS.Endpoint.Address

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: aws-study-vpc

  # サブネット：PublicSubnet
  # AZ1a
  SubnetAZ1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-subnet1a

  # AZ1c
  SubnetAZ1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: ap-northeast-1c
      Tags:
        - Key: Name
          Value: aws-study-subnet1c

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-igw

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # ルートテーブル
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: aws-study-rtb

  RouteInternet:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # 各サブネットとルートテーブルとの関連付け
  # AZ1a
  RouteLocal1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetAZ1a
      RouteTableId: !Ref RouteTable

  # AZ1c
  RouteLocal1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetAZ1c
      RouteTableId: !Ref RouteTable

  # AZ1a：プライベートサブネット
  SubnetPrivate1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.128.0/20
      AvailabilityZone: 
        Fn::Select:
        - 0
        - Fn::GetAZs: !Ref "AWS::Region"
      Tags:
        - Key: Name
          Value: aws-study-subnet-private1-ap-northeast-1a

  # AZ1a：プライベートルートテーブル
  RouteTablePrivate1a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: aws-study-rtb-private1-ap-northeast-1a

  DefaultRoute2:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTablePrivate1a
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociationPrivate1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPrivate1a
      RouteTableId: !Ref RouteTablePrivate1a

  # AZ1c：プライベートサブネット
  SubnetPrivate1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.144.0/20
      AvailabilityZone: 
        Fn::Select:
        - 0
        - Fn::GetAZs: !Ref "AWS::Region"
      Tags:
        - Key: Name
          Value: aws-study-subnet-private2-ap-northeast-1c

  # AZ1c：プライベートルートテーブル
  RouteTablePrivate1c:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: aws-study-rtb-private2-ap-northeast-1c

  SubnetRouteTableAssociationPrivate1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPrivate1c
      RouteTableId: !Ref RouteTablePrivate1c

  # セキュリティーグループ
  # EC2
  SecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AWS Study EC2
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-securityGroup-ec2   

  # RDS
  SecurityGroupRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AWS Study RDS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref SecurityGroupEC2
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-securityGroup-rds  

  # EC2インスタンス
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      # Amazon Linux 2023 の最新AMIをSSMパラメータストアから取得
      ImageId: !Sub "resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
      InstanceType: t2.micro
      KeyName: AkinoriYamamoto
      SubnetId: !Ref SubnetAZ1a
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: stop
      Monitoring: false
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: true
            VolumeSize: 20
      SecurityGroupIds:
        - !Ref SecurityGroupEC2
      Tags:
        - Key: Name
          Value: aws-study-ec2

  # RDS
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceClass: db.t4g.micro
      Port: 3306
      StorageType: gp3
      BackupRetentionPeriod: 7
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: awsstudy
      Engine: mysql
      EngineVersion: 8.0.39
      LicenseModel: general-public-license
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
        - !Ref SecurityGroupRDS
      MultiAZ: false
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: aws-study-rds

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB subnet group created by CloudFormation
      SubnetIds:
        - !Ref SubnetAZ1a
        - !Ref SubnetAZ1c

  RouteTableRDS:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: RDS-Pvt-rt

  # ロードバランサー
  ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-stack-elb
      SecurityGroups:
        - !Ref SecurityGroupEC2
      Subnets:
        - !Ref SubnetAZ1a
        - !Ref SubnetAZ1c
      Scheme: internet-facing
      Type: application
      Tags:
        - Key: Name
          Value: aws-study-elb

  # ターゲットグループ
  ELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: aws-study-target-group
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckProtocol: HTTP
      HealthCheckPath: "/"
      HealthCheckPort: "traffic-port"
      HealthCheckIntervalSeconds: 10
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: aws-study-target-group
      TargetType: instance
      Targets:
        - Id: !Ref EC2
          Port: 8080

  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ELB
      DefaultActions:
        - TargetGroupArn: !Ref ELBTargetGroup
          Type: forward
      Port: 80
      Protocol: HTTP

  # EC2アラーム
  EC2CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmName: aws-study-cpu-utilization-alarm
      AlarmDescription: "Aws-Study.EC2のCPU使用率が 70%以上になりました。"

      Namespace: "AWS/EC2"
      Dimensions:
        - Name: "InstanceId"
          Value: !Ref EC2
      MetricName: "CPUUtilization"
      Unit: "Percent"

      Period: 300
      Statistic: "Average"

      Threshold: 70
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      EvaluationPeriods: 3
      DatapointsToAlarm: 2
      TreatMissingData: "missing"

      ActionsEnabled: true
      AlarmActions:
        - arn:aws:sns:ap-northeast-1:913925038760:AWS-Study-Topic

  # WAF
  WAFIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: WAFv2-IPSet
      Scope: REGIONAL  
      IPAddressVersion: IPV4
      Addresses:
        - "219.59.24.182"

  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: false
        CloudWatchMetricsEnabled: false
        MetricName: AWS-Study-test
      Description: "test"
      Name: AWS-Study-WebACL
      Scope: REGIONAL
      Rules:
        # AWSマネージドルールセット
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: NoUserAgent_HEADER
                - Name: UserAgent_BadBots_HEADER
                - Name: SizeRestrictions_QUERYSTRING
                - Name: SizeRestrictions_Cookie_HEADER
                - Name: SizeRestrictions_BODY
                - Name: SizeRestrictions_URIPATH
                - Name: EC2MetaDataSSRF_BODY
                - Name: EC2MetaDataSSRF_COOKIE
                - Name: EC2MetaDataSSRF_URIPATH
                - Name: EC2MetaDataSSRF_QUERYARGUMENTS
                - Name: GenericLFI_QUERYARGUMENTS
                - Name: GenericLFI_URIPATH
                - Name: GenericLFI_BODY
                - Name: RestrictedExtensions_URIPATH
                - Name: RestrictedExtensions_QUERYARGUMENTS
                - Name: GenericRFI_QUERYARGUMENTS
                - Name: GenericRFI_BODY
                - Name: GenericRFI_URIPATH
                - Name: CrossSiteScripting_COOKIE
                - Name: CrossSiteScripting_QUERYARGUMENTS
                - Name: CrossSiteScripting_BODY
                - Name: CrossSiteScripting_URIPATH
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSCommonRule

  WAFALBAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ELB
      WebACLArn: !GetAtt WAFWebACL.Arn
